// Test case link https://docs.google.com/spreadsheets/d/1qc9rlD38tMFZwy6GJcVLGBSa9BpFnmb3x_JUGOoDk0w/edit?usp=sharing
// |ID    |TEST CASE                                                |TEST DATA                                                |EXPECTED RESULT                                                                                               |
// |TC-01 |	Leave First Name blank	                                |(blank)                                                  |	Should display "This is a required field."                                                                   |
// |TC-02 |	First Name < 3 characters	                              |"Jo"	                                                    |	Should display " First Name must be between 3-10 characters."                                                |
// |TC-03 |	First Name > 10 characters	                            |"JonathanDoe"	                                          |	Should display " First Name must be between 3-10 characters."                                                |
// |TC-04 |	First Name with space only	                            |" "	                                                    |	Should display "This is a required field."                                                                   |
// |TC-05 |	First Name with leading and trailing space	            |" JonathanDoe "	                                        |	"Should automatically trim spaces and only ""JonathanDoe"" is saved. / No error displayed, field accepted."  |
// |TC-06 |	First Name within range	                                |"Ann"	                                                  |	No error displayed, field accepted.                                                                          |     
// |TC-07 |	First Name with special characters or numbers	          |"Ann!3"	                                                |	No error displayed, field accepted.                                                                          |
// |TC-08 |	Leave Last Name blank	                                  |" "	                                                    |	Should display "This is a required field."                                                                   |
// |TC-09 |	Last Name < 3 characters	                              |"Li"	                                                    |	Should display " Last Name must be between 3-10 characters."                                                 | 
// |TC-10 |	Last Name > 10 characters	                              |"AndersonJo"	                                            |	Should display " Last Name must be between 3-10 characters."                                                 | 
// |TC-11 |	Last Name with space only	                              |" "	                                                    |	Should display "This is a required field."                                                                   |  
// |TC-12 |	Last Name with leading and trailing space	              |" AndersonJo "	                                          |	"Should automatically trim spaces and only ""AndersonJo"" is saved. / No error displayed, field accepted."   |
// |TC-13 |	Last Name within range	                                |"Smith"	                                                |	No error displayed, field accepted.                                                                          |   
// |TC-14 |	Leave Email blank	                                      |" "	                                                    |	Should display "This is a required field."                                                                   |  
// |TC-15 |	Invalid email	                                          |"user@"	                                                |	Should display "Please enter a valid email address."                                                         |  
// |TC-16 |	Missing '@'	                                            |"user.com"	                                              |	Should display "Please enter a valid email address."                                                         |    
// |TC-17 |	Invalid domain	                                        |"user@mail"	                                            |	Should display "Please enter a valid email address."                                                         |  
// |TC-18 |	Email with space only	                                  |" "	                                                    |	Should display "This is a required field."                                                                   |  
// |TC-19 |	Email with leading and trailing space	                  |" user@test.com "                                        | Should automatically trim spaces and only ""user@test.com"" is saved. /No error displayed, field accepted.   |
// |TC-20 |	Valid email	                                            |"user@test.com"	                                        |	No error displayed, field accepted.                                                                          |     
// |TC-21 |	Leave Password blank	                                  |(blank)	                                                |	Should display "This is a required field."                                                                   | 
// |TC-22 |	Password with < 8 characters	                          |"<An1!"	                                                |	Should display "Password must be at least 8 characters."                                                     |  
// |TC-23 |	Password with missing uppercase	                        |"test123!"	                                              |	Should display "Password must include uppercase, lowecase, number, special character."                       | 
// |TC-24 |	Password with missing lowercase	                        |"TEST123!"	                                              |	Should display "Password must include uppercase, lowecase, number, special character."                       |  
// |TC-25 |	Password with missing number	                          |"TestTest!"	                                            |	Should display "Password must include uppercase, lowecase, number, special character."                       |
// |TC-26 |	Password with missing special character	                |"Test1234"	                                              |	Should display "Password must include uppercase, lowecase, number, special character."                       |
// |TC-27 |	Password with space only	                              |" "	                                                    |	Should display "This is a required field."                                                                   |  
// |TC-28 |	Password with leading and trailing space	              |" Test!123 "	                                            |	"Should automatically trim spaces and only ""Test!123"" is saved. / No error displayed, field accepted."     |
// |TC-29 |	Valid password	                                        |"Test!123"	                                              |	No error displayed, field accepted.                                                                          |   
// |TC-30 |	Leave Confirm Password blank	                          |(blank)	                                                |	Should display "This is a required field."                                                                   |  
// |TC-31 |	Confirm Password does not match password	              |"Password: "Test!123" / Confirm Password: "Test123!"	    | Should display "Password does not match."                                                                    |    
// |TC-32 |	Confirm Password with space only	                      |"Password: "Test!123" / Confirm Password: " ""	          | Should display "This is a required field."                                                                   | 
// |TC-33 |	Confirm Password with leading and trailing space        | "Password: "Test!123" / Confirm Password: " Test!123 "	| Should automatically trim spaces and only "Test!123" is saved. / No error displayed, field accepted."        |
// |TC-34 |	Matches password	                                      |"Password: "Test!123" / Confirm Password: "Test!123"	    | No error displayed, field accepted.                                                                          | 
// |TC-35 |	Not checked Terms & Conditions	                        |T&C left unchecked                                     	| Should display "Please accept Terms & Conditions."                                                           | 
// |TC-36 |	Checked Terms & Conditions	                            |T&C checked	                                            | No error displayed, field accepted.                                                                          |    
// |TC-37 |	All fields blank	                                      |(blank)	                                                | Should display "This is a required field." on each fields and T&C error.                                     | 
// |TC-38 |	Valid fields and T&C not checked	                      |All fields valid, T&C unchecked	                        | Should display "Please accept Terms & Conditions."                                                           | 
// |TC-39 |	Mix of valid and invalid fields, T&C checked	          |First Name too short, others valid                     	| Should display appropriate field errors.                                                                     | 
// |TC-40 |	All valid fields and T&C checked	                      |All fields valid, T&C checked	                          | All fields accepted, sign up submits successfully, shows success message or redirects to account page.       |
// |TC-41 |	Page is refresh while form is not yet submitted	        |	                                                        | All fields are cleared and data is not saved.                                                                |     
// |TC-42 |	Back button is clicked while form is not yer submitted	|	                                                        | All fields are cleared and data is not saved.                                                                |        